### ISSUE TITLE
Add a database connection

### ISSUE THREAD

**Issue by tanwride** [bchastain/insightsworkbook#1]
Hi,

Great work with this script. It's awesome and very helpful.  I am trying to add a database connection (relationalCatalogService) to a page on a workbook using a similar python script to yours.  Any tips or tricks on how to add data to a page from a db connection using python? Thanks

**Comment by bchastain** [comment]
Hey, glad someone's getting some use out of this. I haven't updated it in quite awhile. My suggestion would be to use your browser's Developer tools and watch the network trace as you manually add a database connection. That's pretty much how I reverse engineered all of this.

**Comment by tanwride** [comment]
Thank you for the response! This has been really helpful for a workflow I am creating.  I work with multiple vm's and need to create wb's each time a new vm is created.  These are self contained environments so a distributed collaboration doesn't work for me in this scenario, leaving me to write a python script so I don't have to recreate the work over and over and over..
